kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-cstor-pvc
spec:
  storageClassName: openebs-sc-statefulset
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
